name: oa_main
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:                # Importante  
    sdk: flutter
  flutter_slidable: ^1.1.0              # Importante  
  image_picker: ^0.8.4+6                # Importante  
  table_calendar: ^3.0.3                # Importante  
  flutter_native_image: ^0.0.6+1        # Importante Ver Substituto

  font_awesome_flutter: ^9.2.0          # Basico
  get: ^4.6.1                           # Basico
  get_storage: ^2.0.3                   # Basico
  google_fonts: ^2.2.0                  # Basico
  supabase: ^0.2.10                     # Basico

  oa_fone: ^1.0.2                       # Package Propria 
  via_cep_flutter: ^0.2.2               # Alterar para Propria 

  flutter_cache_manager: ^3.3.0         # Maquiagem

  mask_text_input_formatter: ^2.0.0     # Rever
  staggered_grid_view_flutter: ^0.0.4   # Dispensavel
  transparent_image: ^2.0.0             # Dispensavel
  toggle_switch: ^1.4.0                 # Dispensavel
  flutter_colorpicker: ^1.0.3           # Dispensavel
  lottie: ^1.2.1                        # Dispensavel
  intl: ^0.17.0                         # Observar
  #cupertino_icons: ^1.0.2           
  #image_downloader: ^0.31.0

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/
