name: oa_main
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  supabase: ^0.2.10
  oa_fone: ^1.0.2
  flutter_slidable: ^1.1.0
  mask_text_input_formatter: ^2.0.0
  flutter_cache_manager: ^3.3.0
  staggered_grid_view_flutter: ^0.0.4
  transparent_image: ^2.0.0
  toggle_switch: ^1.4.0
  flutter_colorpicker: ^1.0.3
  via_cep_flutter: ^0.2.2
  image_picker: ^0.8.4+6
  table_calendar: ^3.0.3

  #image_downloader: ^0.31.0
  #lottie: ^1.2.1

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/
